version: 0.0
Resources:
  - LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "LambdaFunction"
        Alias: "LambdaFunctionAlias"
        CurrentVersion: "1"
        TargetVersion: "2"